import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
    // Users: Synced from Clerk
    users: defineTable({
        tokenIdentifier: v.string(), // Clerk ID
        orgId: v.optional(v.string()), // Organization ID
        role: v.optional(v.string()), // 'admin' | 'member'
        name: v.optional(v.string()),
        email: v.optional(v.string()),
    }).index("by_token", ["tokenIdentifier"])
        .index("by_org", ["orgId"]),

    // Agents: Configuration for each Org's agents
    agents: defineTable({
        orgId: v.string(),
        name: v.string(), // 'Co-CEO', 'Sales', 'Brand', 'Knowledge'
        isActive: v.boolean(),
        config: v.any(), // JSON config (prompts, model settings)
    }).index("by_org", ["orgId"]),

    // Memories: Long-term memory (synced from Mem0)
    memories: defineTable({
        orgId: v.string(),
        agentId: v.string(), // Which agent created this?
        content: v.string(),
        embedding: v.optional(v.array(v.float64())), // Vector for RAG
        tags: v.optional(v.array(v.string())),
    }).index("by_org", ["orgId"])
        .vectorIndex("by_embedding", {
            vectorField: "embedding",
            dimensions: 1536, // OpenAI dimensions
            filterFields: ["orgId"],
        }),

    // Leads: Found by Sales Agent
    leads: defineTable({
        orgId: v.string(),
        companyName: v.string(),
        website: v.optional(v.string()),
        score: v.number(), // 0-100
        status: v.string(), // 'new', 'contacted', 'qualified'
        data: v.any(), // Full Exa/LLM data
        lastContactedAt: v.optional(v.number()),
    }).index("by_org", ["orgId"])
        .index("by_status", ["orgId", "status"]),

    // Assets: Created by Brand Agent
    assets: defineTable({
        orgId: v.string(),
        type: v.string(), // 'image', 'pdf', 'text'
        url: v.string(),
        prompt: v.string(),
        status: v.string(), // 'generating', 'ready', 'failed'
        createdAt: v.number(),
    }).index("by_org", ["orgId"]),

    // Knowledge: Ingested by Knowledge Agent
    knowledge: defineTable({
        orgId: v.string(),
        url: v.string(),
        summary: v.optional(v.string()),
        entities: v.optional(v.any()), // JSON graph data
        embedding: v.optional(v.array(v.float64())),
        ingestedAt: v.number(),
    }).index("by_org", ["orgId"])
        .vectorIndex("by_embedding", {
            vectorField: "embedding",
            dimensions: 1536,
            filterFields: ["orgId"],
        }),

    // Proposals: Generated by Proposal Agent
    proposals: defineTable({
        orgId: v.string(),
        prospectName: v.string(),
        prospectUrl: v.string(),
        painPoints: v.string(),
        content: v.any(), // JSON output from agent
        presentationUrl: v.optional(v.string()), // Gamma deck URL
        pdfUrl: v.optional(v.string()), // Gamma PDF export URL
        pptxUrl: v.optional(v.string()), // Gamma PowerPoint export URL
        status: v.string(), // 'draft', 'sent'
        views: v.optional(v.number()), // Analytics: View count
        lastViewedAt: v.optional(v.number()), // Analytics: Timestamp
        createdAt: v.number(),
        updatedAt: v.optional(v.number()),
    }).index("by_org", ["orgId"]),

    // Telegram Users: Mapping Chat ID to Org
    telegram_users: defineTable({
        chatId: v.number(),
        userId: v.optional(v.id("users")),
        orgId: v.optional(v.string()),
        username: v.optional(v.string()),
    }).index("by_chat", ["chatId"]),

    // Audit Logs: For security/debugging
    audit_logs: defineTable({
        orgId: v.string(),
        action: v.string(),
        actorId: v.optional(v.string()),
        details: v.any(),
        timestamp: v.number(),
    }).index("by_org", ["orgId"]),
});